# Generated by Django 3.0.6 on 2020-05-27 13:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Kategoriya Nomi')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Maxsulot Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavfsifi')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='media_images', verbose_name='Maxsulot Rasmi')),
                ('currency', models.CharField(choices=[(None, ''), ("so'm", "so'm"), ('$', 'dollor'), ('euro', 'euro'), ('ruble', 'ruble')], default='', max_length=5, verbose_name='valyuta turi')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000000)], verbose_name='Maxsulot Narxi')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='Product.Category', verbose_name='Maxsulot Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_caption', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, max_length=250, null=True, upload_to='media_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
            ],
        ),
    ]
